name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main  # Cambia 'main' si tu rama principal tiene otro nombre

jobs:
  build:
    runs-on: ubuntu-24.04  # Especificar la versión puede ayudar a prevenir incompatibilidades[_{{{CITATION{{{_2{Actions: new images and ubuntu-latest changes - GitHub Changelog](https://github.blog/changelog/2024-09-25-actions-new-images-and-ubuntu-latest-changes/)

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'  # Ajusta esta versión según tus necesidades
      - name: Install dependencies
        run: bundle install
      - name: Build Jekyll site
        run: bundle exec jekyll build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
