name: Notify IndexNow

on:
  push:
    branches: ["blog"]
      
jobs:
  notify-indexnow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Notify IndexNow
        run: |
          # Define tu clave y la URL de tu sitio
          KEY="135E9EB7CBBE4F1A8A718DB5461FF2FF"  # Tu clave de IndexNow
          SITE_URL="https://www.enfaseterminal.com"  # Tu URL

          # Envía la solicitud a IndexNow usando curl
          curl -X POST "https://api.indexnow.org/indexnow" \
          -H "Content-Type: application/json" \
          -d '{
            "host": "'"$SITE_URL"'",
            "key": "'"$KEY"'",
            "keyLocation": "'"$SITE_URL/$KEY.txt"'",
            "urlList": [
              "'"$SITE_URL"'"
            ]
          }'
