      - name: Notify IndexNow
        run: |
          # Define tu clave y la URL de tu sitio
          KEY="135E9EB7CBBE4F1A8A718DB5461FF2FF"  # Tu clave de IndexNow
          SITE_URL="https://www.enfaseterminal.com"  # Tu URL

          # Envía la solicitud a IndexNow usando curl y muestra la respuesta
          echo "Enviando solicitud a IndexNow..."
          RESPONSE=$(curl -X POST "https://api.indexnow.org/indexnow" \
          -H "Content-Type: application/json" \
          -d '{
            "host": "'"$SITE_URL"'",
            "key": "'"$KEY"'",
            "keyLocation": "'"$SITE_URL/$KEY.txt"'",
            "urlList": [
              "'"$SITE_URL"'"
            ]
          }' -w "\nCódigo de respuesta: %{http_code}\n")

          echo "Respuesta de IndexNow:"
          echo "$RESPONSE"
